[project]
name = "finacial-report"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "json-repair>=0.57.1",
    "openai>=1.0.0",
    "pdfminer-six>=20260107",
    "pypdf>=6.6.2",
    "python-dotenv>=1.2.1",
]
